board/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, voter_views

app_name = 'board'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    #voter_views.py
    path('vote/question/<int:question_id>', voter_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>', voter_views.vote_answer, name='vote_answer'),
    #path('url명', 뷰에서.가져올함수)
    #path('', views.index),
    #path('testpage/', views.test),
    #path('<int:question_id>', views.detail),

]

common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    #path('url명', 뷰에서.가져올함수)

    #path('testpage/', views.test),
    #path('<int:question_id>', views.detail),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# ORM
# 데이터베이스의 데이터를 조회하거나 저장하기위해 원래는
# 쿼리(SQL)을 사용했지만 Django에서는
# 데이터베이스 테이블을 '모델화'해서 사용하고 쿼리들을
# Django 기준 python 코드로 처리하는 방법.

# ORM의 특징
# 개발자만의 쿼리(sql)을 만들기가 어렵다.
# 쿼리를 잘못 작성할 가능성이 낮아진다(간단한 명령에 한해서)
# DBMS를 변경(이관)할때 쿼리를 바꿀 필요가 없다.

# 모델 작성
# 질문, 답변 모델을 생성
# 질문모델
# subject : 질문의 제목
# content : 질문의 내용
# create_date : 질문을 작성한 일시

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question') # 추천인

    def __str__(self):
        return self.subject
# 답변모델
# question : 질문
# content: 답변의 내용
# create_date : e답변 작성 일시.
# 컬럼에 null을 허용하고 싶다면 null=True를 추가
# null=True : 컬럼에 null을 허용하는 속성
# blank=True : 어떤 조건으로도 값을 비워둘수 있음.
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')  # 추천인
# 질문과 답변에 댓글기능 추가 21.10.05
# author : 댓글의 글쓴이
# content : 댓글 내용
# create_date : 댓글 작성일
# modify_date : 댓글 수정일
# question : 이 댓글이 달린 질문
# answer : 이 댓글이 달린 답변
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

board/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Q, Count
from ..models import Question


# Create your views here.

# 메인 페이지 작성
# 질문 목록 출력
# 21.09.17 조준모
def index(request):
    # Question.objects.order_by('-create_date')
    # Question 모델에서 객체를 참조하는데 / -가 붙어 있으면 해당 객체를 기준으로 역순정렬
    # 역순으로 정렬해올것. (객체는 create_date)

    # 페이징처리 추가 21.09.24 조준모

    # 페이징 처리 관련 템플릿 태그 속성.(템플릿단 페이징 처리 속성)
    # .count : 전체 게시물 개수
    # .per_page : 페이지당 보여줄 게시물 개수
    # .page_range : 페이지 범위
    # number : 현재 페이지 번호
    # previous_page_number : 이전 페이지 번호
    # next_page_number : 다음 페이지 번호
    # has_previous : 이전 페이지 유무
    # has_next : 다음 페이지 유무
    # start_index : 현재 페이지 시작 인덱스
    # end_index : 현재 페이지 끝 인덱스

    # 페이지의 입력 파라미터 추가.
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    # 조회
    #question_list = Question.objects.order_by('-create_date')
    if so == "recommend":
        # annotate = 기존의 모델에 임시로 속성을 부여하는 장고의 함수
        # voter(추천수)를 카운트 받아 저장후 정렬조건에 사용.
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif so =='popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | # __icontains : 컬럼의 조회조건 부여
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()


    # 페이징처리 기능 구현
    pagenator = Paginator(question_list, 10)# 페이지당 10개씩
    page_obj = pagenator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'question_list.html', context)

def detail(request, question_id):
    # 글의 제목과 내용 출력
    question = Question.objects.get(id=question_id)
    return render(request, 'question_detail.html', {'question': question})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,
          initial-scale=1, shring-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/boardStyle.css'%}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock %}

    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand text-white" href="{% url 'board:index' %}">실습프로젝트</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link text-white" href="{% url 'common:logout' %}">{{user.username}}(로그아웃)</a>
        {% else %}
        <a class="nav-link text-white" href="{% url 'common:login' %}">로그인</a>
        {% endif %}
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>

  </div>
</nav>


{% block content %}
{% endblock %}

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}<!--필드에러 검출-->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %} <!-- form for end-->
    {% for error in form.non_field_errors %} <!-- None필드 에러 검출-->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
    {% endfor %}
{% endif %}

<!--
 필드에러 : 사용자가 입력한 필드값에 대한 오류. 값이 누락되거나
           필드의 형식이 일치하지 않는 경우에 발생.
None필드에러 : 필드값과 상관없이 다른이유 혹은 외부의 원인에 의해 발생하는 에러

 -->

templates/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1">
             <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                 {{question.voter.count}}
             </div>
             <a href="#" data-uri="{% url 'board:vote_question' question.id %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">
               추천
             </a>
        </div>
        <div class="col-11"><!--질문 영역-->
        <div class="card">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            {% if request.user == question.author %}
            <div class="my-3">
                <a href="{% url 'board:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'board:question_delete' question.id  %}">삭제</a>
            </div>
            {% endif %}
            <!-- 질문 댓글 Start -->
            {% if question.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in question.comment_set.all %}
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'board:comment_modify_question' comment.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete"
                       data-uri="{% url 'board:comment_delete_question' comment.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'board:comment_create_question' question.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>
            </div>
            <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="row my-3">
    <div class="col-1">  <!-- 추천영역 -->
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
        <a href="#" data-uri="{% url 'board:vote_answer' answer.id  %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">  <!-- 답변영역 -->
    <div class="card">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            {% if request.user == answer.author %}
            <div class="my-3">
                <a href="{% url 'board:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'board:answer_delete' answer.id  %}">삭제</a>
            </div>
            {% endif %}
            {% if answer.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in answer.comment_set.all %}
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'board:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete"
                       data-uri="{% url 'board:comment_delete_answer' comment.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'board:comment_create_answer' answer.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>
            </div>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function(){
        if(confirm("정말로 추천?")){
            location.href = $(this).data('uri');
        }
    });


});
</script>
{% endblock %}

templates/question_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %} >최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif%} >추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>

        </div>
    </div>


    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>추천</th>
                <th>제목</th>
                <th>글쓴이</th>
                <th>작성일자</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %} <!-- 분기 시작 -->
        {% for question in question_list %}<!-- 반복 시작 -->
            <tr>
                <!--
                21.09.27 번호 출력 변경
                번호 = 전체건수 - 시작인덱스 - 현재인덱스 +1 
                -->
                <td>{{ question_list.paginator.count|sub:question_list.start_index| sub:forloop.counter0|add:1}}</td>
                <td>
                    {% if question.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a> <!-- 객체출력 (객체.속성) -->
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
        {% endfor %}<!-- 반복 종료 -->
        {% else %}
            <tr>
                <td>질문이 없습니다.</td>
            </tr>
        {% endif %} <!-- 분기종료 -->
        </tbody>
    </table>
    <!-- 페이징처리 시작-->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지
             hav_previous :이전페이지 유무
             previous_page_number : 이전페이지 번호
          -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number}}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" aria-disabled="true" tabindex="-1" href="#">이전</a>
        </li>
        {% endif %}
        <!--이전페이지 처리 끝-->
        <!-- 페이지리스트-->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 페이지리스트 처리 끝-->
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{question_list.next_page_number}}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" aria-disabled="true" tabindex="-1" href="#">다음</a>
        </li>
        {% endif %}
        <!-- 다음페이지 처리 끝-->
    </ul>
    <!-- 페이징처리 끝-->
    <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".page-link").on('click', function(){
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function(){
        $("#kw").val($(".kw").val());
        $("#page").val(1); //검색 버튼 클릭시 1페이지부터 조회
        $("#searchForm").submit();

    });

    $(".so").on('change', function(){
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

});
</script>
{% endblock %}
<!--
템플릿 태그 : html에 모델의 속성등을 불러오기 위한 문장.
1. 분기문(조건문)
2. 반복문.
3. 객체출력.
for문 안에는 forloop라는 객체를 사용할수 있음.
forloop.counter : 루프 내의 순서로 1부터 표시
forloop.counter() : 0부터 표시
forloop.first : 루프 첫번째 순서인 경우 True
forloop.last : 마지막 순서인경우 True
-->

templates/question_list_bak0924.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일자</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %} <!-- 분기 시작 -->
        {% for question in question_list %}<!-- 반복 시작 -->
            <tr>
                <td>{{ forloop.counter}}</td>
                <td>
                    <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a> <!-- 객체출력 (객체.속성) -->
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
        {% endfor %}<!-- 반복 종료 -->
        {% else %}
            <tr>
                <td>질문이 없습니다.</td>
            </tr>
        {% endif %} <!-- 분기종료 -->
        </tbody>
    </table>
    <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

<!--
템플릿 태그 : html에 모델의 속성등을 불러오기 위한 문장.
1. 분기문(조건문)
2. 반복문.
3. 객체출력.
for문 안에는 forloop라는 객체를 사용할수 있음.
forloop.counter : 루프 내의 순서로 1부터 표시
forloop.counter() : 0부터 표시
forloop.first : 루프 첫번째 순서인 경우 True
forloop.last : 마지막 순서인경우 True
-->

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>테스트페이지</title>
</head>
<body>
  <h1>테스트 중입니다.</h1>
  <h2>템플릿 테스트.</h2>
</body>
</html>